CHUNK_SIZE: 800
CHUNK_OVERLAP: 80
NUM_RESULTS: 4
MAX_AGENT_ITERATIONS: 3
MAX_CRITIQUE_ITERATIONS: 1
NUM_CTX: 8192
DATA_PATH: "data"
VECTORSTORE_PATH: "vectorstore"
EMBEDDINGS: "sentence-transformers/all-MiniLM-L6-v2"
NORMALIZE_EMBEDDINGS: true
DEVICE: "cpu"
VECTOR_SPACE: "cosine"
LLM: "llama3.2:3b"
